runtime: python37
service: default

handlers:
  - url: /
    static_files: public/index.html
    upload: public/*

  - url: /(.*)/
    static_files: public/\1/index.html
    upload: public/*

  - url: /
    static_dir: public/
