# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git init
        git remote add origin https://github.com/SkYNewZ/lemairepro.fr.git
        git fetch --depth=1 origin $COMMIT_SHA
        git reset --hard FETCH_HEAD
        git submodule update --init

  - name: skynewz/hugo:v0.54.0
    args: ["--minify", "--gc"]

  - name: gcr.io/cloud-builders/gcloud-slim
    args: ["app", "deploy", "app.yaml"]
